<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE Oglasi [
<!ELEMENT Oglasi (Oglas+)>
<!ELEMENT Oglas (Kategorija,DatumIsteka,Cena,Deskripcija,Tagovi*,Email)>
<!ELEMENT Kategorija (#PCDATA)>
<!ELEMENT DatumIsteka (#PCDATA)>
<!ELEMENT Cena (#PCDATA)>
<!ATTLIST Cena valuta (rsd | euros | pounds | dollars) #REQUIRED>
<!ELEMENT Deskripcija (#PCDATA)>
<!ELEMENT Tagovi (Tag+)>
<!ELEMENT Tag (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ATTLIST Email pristup (privatni | sluzbeni) #REQUIRED>
]> -->
<!DOCTYPE Oglasi SYSTEM "../DTDstorage/oglasi.dtd" >
<Oglasi>
    <Oglas>
        <Kategorija>Stanovi</Kategorija>
        <DatumIsteka>05-07-2022</DatumIsteka>
        <Cena valuta="rsd">3400.99</Cena>
        <Deskripcija>Jednosoban stan u strogom centru Borce bez kanalizacije sve na septicku jamu!</Deskripcija>
        <Tagovi>
            <Tag>Centar</Tag>
            <Tag>Jednosoban</Tag>
        </Tagovi>
        <Email pristup="privatni">pera.peric@gmail.com</Email>
    </Oglas>

     <Oglas>
        <Kategorija>Alati</Kategorija>
        <DatumIsteka>05-06-2022</DatumIsteka>
        <Cena valuta="euros">4200</Cena>
        <Deskripcija>Set alata za popravku polomljenih sijalica marke Bosch u savrsenom retko koriscenom stanju!</Deskripcija>
        <Tagovi>
            <Tag>Nekorisceno</Tag>
        </Tagovi>
        <Email pristup="sluzbeni">mara.maric@gmail.com</Email>
    </Oglas>

</Oglasi>